dist: bionic
language: cpp
os:
  - linux
  - osx
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -qq; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y scilab; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew cask install homebrew/cask-versions/adoptopenjdk8; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew cask install scilab; fi

  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then scilab -nw -version; true; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then '/Applications/Scilab-6.0.2.app/Contents/MacOS/bin/scilab' -nw -version; true; fi
script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then scilab -nw -e 'result = exec("builder.sce", "errcatch"); exit(result)'; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then scilab -nw -e 'result = exec("loader.sce", "errcatch"); exit(result)'; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then '/Applications/Scilab-6.0.2.app/Contents/MacOS/bin/scilab' -nw -e 'result = exec("builder.sce", "errcatch"); exit(result)'; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then '/Applications/Scilab-6.0.2.app/Contents/MacOS/bin/scilab' -nw -e 'result = exec("loader.sce", "errcatch");  exit(result)'; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then '/Applications/Scilab-6.0.2.app/Contents/MacOS/bin/scilab' -nw -e 'result = exec("cleaner.sce", "errcatch"); exit(result)'; fi
